spring:
  config:
    import: "optional:classpath:bootstrap.yml"

  datasource:
    url: jdbc:mysql://localhost:3306/pulse
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  servlet:
    context-path: "/user-service"