server:
  port: 8504

spring:
  application:
    name: product-service
  cache:
    type: redis
  redis:
    host: redis
    port: 6379
    timeout: 60000

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/